[tool.poetry]
name = "pydew"
version = "0.1.0"
description = ""
authors = ["João Rafael <joaoraf@me.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pygame = "*"
pytmx = "^3.31"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
